# Generated by Django 5.2 on 2025-04-06 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_learned', 'Not Learned'), ('in_progress', 'In Progress'), ('learned', 'Learned')], default='not_learned', max_length=20)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('topic_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='TopicDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='main.topic')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_topics', to='main.topic')),
            ],
            options={
                'verbose_name': 'Topic Dependency',
                'verbose_name_plural': 'Topic Dependencies',
                'unique_together': {('source', 'target')},
            },
        ),
    ]
