# Generated by Django 5.2 on 2025-04-06 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_remove_topic_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CodeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_source', models.CharField(choices=[('cursor_ai', 'Cursor AI Generation'), ('manual_edit', 'Manual Edit'), ('git_commit', 'Git Commit'), ('scheduled_scan', 'Scheduled Scan')], max_length=20)),
                ('change_id', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True)),
                ('diff_content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extracted_topics', models.ManyToManyField(blank=True, related_name='source_changes', to='main.topic')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_changes', to='main.project')),
            ],
            options={
                'verbose_name': 'Code Change',
                'verbose_name_plural': 'Code Changes',
                'ordering': ['-created_at'],
            },
        ),
    ]
