# Generated by Django 4.2.7 on 2025-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_metadata_codechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_id'], name='main_projec_project_f31a71_idx'),
        ),
    ]
