# Generated by Django 4.2.7 on 2025-04-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['topic_id'], name='main_topic_topic_i_47051e_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status'], name='main_topic_status_b86aaa_idx'),
        ),
    ]
